name: Flet Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Flet and deps
        run: |
          python -m pip install --upgrade pip
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ابنِ الـ APK (عدّل --module-name إذا اسم ملف الدخول غير "main")
      - name: Build APK
        run: |
          flet build apk --split-per-abi

      # ارفع ملفات الـ APK كـ Artifact
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/apk/*.apk
          if-no-files-found: error
